db.places.insert(
    
)


db.places.insertMany([
    {
        name: 'Hala''s Grill',
        description: 'Modest counter-serve for Middle Eastern bowls with protein options, plus sides.',
        placeType: 'Food',
        tags: [ 'Middle Eastern', 'Healthy', 'Local', 'Home-Made', 'Chauncey', 'Bowl', 'Fries' ],
        location: { type: 'Point', coordinates: [40.423304605885455, -86.907737172374] },
        reviews: [ ],
        images: ['https://tinyurl.com/halaslogo', 'https://tinyurl.com/halabowl', 'https://tinyurl.com/halasfries'],
        address: '135 S Chauncey Ave #2G, West Lafayette, IN 47906',
        googleMap: 'https://www.google.com/maps/place/Hala''s+Grill/@40.4229005,-86.9078096,17z/data=!3m1!4b1!4m6!3m5!1s0x8812e373c4bc8363:0x1df2c0530eee7a7a!8m2!3d40.4229005!4d-86.9078096!16s%2Fg%2F11hkfkjj_g',
        website: 'https://www.halasgrill.com/'
    },
    {
        name: 'Five Guys',
        description: 'Fast-food chain with made-to-order burgers, fries & hot dogs, milkshakes, and free peanuts while you wait.',
        placeType: 'Food',
        tags: [ 'Fast Food', 'American', 'Burgers', 'Fries', 'Milkshakes', 'Chain', 'Chauncey' ],
        location: { type: 'Point', coordinates: [40.42343994609269, -86.90795109977412] },
        reviews: [ ],
        images: ['https://tinyurl.com/fiveguysfood', 'https://tinyurl.com/5guysinsidewl'],
        address: '135 S Chauncey Ave Suite 1-K, West Lafayette, IN 47906',
        googleMap: 'https://www.google.com/maps/place/Five+Guys/@40.4233731,-86.9122599,17.05z/data=!4m6!3m5!1s0x8812e2aed99721e9:0x2a65fca44b4f0116!8m2!3d40.4233321!4d-86.9080151!16s%2Fg%2F1tvq4qs0',
        website: 'https://restaurants.fiveguys.com/135-s-chauncey-avenue'
    },
    {
        name: 'Insomnia Cookies',
        description: 'Bakery chain known for warm & fresh cookies, open late-night, and also selling ice cream.',
        placeType: 'Food',
        tags: ['Desserts', 'Cookies', 'Ice Cream', 'Open Late', 'Chain', 'On Campus'],
        location: { type: 'Point', coordinates: [40.431694360504636, -86.91303583596788] },
        reviews: [ ],
        images: ['https://tinyurl.com/insomniacookieslogo', 'https://tinyurl.com/insomniacookiespurdue'],
        address: '602 W Stadium Ave, West Lafayette, IN 47906',
        googleMap: 'https://www.google.com/maps/place/Insomnia+Cookies/@40.4315727,-86.9151089,17z/data=!4m15!1m8!3m7!1s0x8812fd4d4fe0373f:0x6ba1b40af4af0021!2sInsomnia+Cookies!8m2!3d40.4315727!4d-86.9130013!10e1!16s%2Fg%2F1vxw8wg_!3m5!1s0x8812fd4d4fe0373f:0x6ba1b40af4af0021!8m2!3d40.4315727!4d-86.9130013!16s%2Fg%2F1vxw8wg_',
        website: 'https://insomniacookies.com/menu/17'
    },
    {
        name: 'Mad Mushroom',
        description: 'Local pizza chain dishing up a wide variety of pies, grinders, pasta & salads. Most known for its Cheesestix.',
        placeType: 'Food',
        tags: [ 'Pizza', 'American', 'Italian', 'Local', 'Chain', 'Chauncey', 'On Campus', 'Open Late', 'Alcohol' ],
        location: { type: 'Point', coordinates: [40.42426763341673, -86.90904218988186] },
        reviews: [ ],
        images: ['https://tinyurl.com/madmushroomlogo', 'https://tinyurl.com/madmushpies'],
        address: '320 W State St, West Lafayette, IN 47906',
        googleMap: 'https://www.google.com/maps/place/Mad+Mushroom/@40.4241043,-86.9111746,17z/data=!3m1!4b1!4m6!3m5!1s0x8812fd4d1c8bf8cb:0xf26797ec22ddf82c!8m2!3d40.4241002!4d-86.9089859!16s%2Fg%2F12cpby27w',
        website: 'https://www.madmushroom.com/west-lafayette'
    },
    {
        name: 'Maru Sushi',
        description: 'Happening eatery serving up sushi & other traditional Japanese staples in a minuscule space.',
        placeType: 'Food',
        tags: [ 'Asian', 'Japanese', 'Sushi', 'Chauncey', 'Local' ],
        location: { type: 'Point', coordinates: [40.42470168147317, -86.90665652715337] },
        reviews: [ ],
        images: ['https://tinyurl.com/marusushilogopurdue', 'https://tinyurl.com/marusushipurduesushiplate'],
        address: '102 N Chauncey Ave D, West Lafayette, IN 47906',
        googleMap: 'https://www.google.com/maps/place/Maru+Sushi/@40.4245016,-86.9089847,17z/data=!3m1!4b1!4m6!3m5!1s0x8812e2a936645567:0xde255f15b5d68628!8m2!3d40.4245016!4d-86.906796!16s%2Fg%2F1vzg2vgk',
        website: 'https://maru-sushi.us/'
    },
    {
        name: 'Bruno''s Pizza and Big O''s Sports Room',
        description: 'American, Italian & some German dishes, plus a full bar, in a Swiss chalet-type setting.',
        placeType: 'Food',
        tags: [ 'Pizza', 'American', 'German', 'Italian', 'Alcohol', 'Local', 'Wabash Landing' ],
        location: { type: 'Point', coordinates: [40.42252768794087, -86.90299580387695] },
        reviews: [ ],
        images: ['https://tinyurl.com/brunoslogowl', 'https://tinyurl.com/brunospizzawlpizza', 'https://tinyurl.com/brunosdoughsplwl'],
        address: '212 Brown St, West Lafayette, IN 47906',
        googleMap: 'https://www.google.com/maps/place/Bruno''s+Pizza+and+Big+O''s+Sports+Room/@40.4223276,-86.9051094,17z/data=!4m15!1m8!3m7!1s0x8812e2a82517cf6d:0x81d1a879bb1aecda!2sBruno''s+Pizza+and+Big+O''s+Sports+Room!8m2!3d40.4223276!4d-86.9029207!10e1!16s%2Fg%2F1tgyx9kh!3m5!1s0x8812e2a82517cf6d:0x81d1a879bb1aecda!8m2!3d40.4223276!4d-86.9029207!16s%2Fg%2F1tgyx9kh',
        website: 'http://brunodough.com/'
    },
    {
        name: 'Strings Ramen',
        description: 'Restaurant with great ambiance offering Ramen as well as other Japanese side dishes.',
        placeType: 'Food',
        tags: [ 'Asian', 'Japanese', 'Ramen', 'Chauncey', 'Chain', 'Local' ],
        location: { type: 'Point', coordinates: [40.42417961049075, -86.90706417318749] },
        reviews: [ ],
        images: ['https://tinyurl.com/stringsramenlogo', 'https://tinyurl.com/stringsramenfood'],
        address: '103 N Chauncey Ave, West Lafayette, IN 47906',
        googleMap: 'https://www.google.com/maps/place/Strings+Ramen+Purdue/@40.4240367,-86.9092636,17z/data=!4m6!3m5!1s0x8812e3e71476fe81:0x489bc752b37b9cad!8m2!3d40.4240367!4d-86.9070749!16s%2Fg%2F11rwrz6c32',
        website: 'https://www.stringsramen.com/'
    },
    {
        name: '',
        description: '',
        placeType: 'Food',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Food',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Food',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: 'Red Wok',
        description: 'Chinese Food Place',
        placeType: 'Food',
        tags: [ 'Chinese', 'Asian', 'Open Late', 'Local', 'Chauncey' ],
        location: { type: 'Point', coordinates: [ 40.42313730000001, -86.9087126 ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: 'Chipotle',
        description: 'Mexican Food Place',
        placeType: 'Food',
        tags: [ 'Mexican', 'Healthy', 'Chain' ],
        location: { type: 'Point', coordinates: [ 40.4236301, -86.9101227 ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: 'Silver Dipper',
        description: 'Ice Cream Place',
        placeType: 'Food',
        tags: [ 'Ice Cream', 'Desserts', 'Local', 'Wabash Landing' ],
        location: { type: 'Point', coordinates: [ 40.4197746, -86.91205520000001 ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Cafe',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Cafe',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Cafe',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Cafe',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Cafe',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Cafe',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Cafe',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Study',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Study',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Study',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Study',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Study',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Study',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Study',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Study',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Study',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: 'WALC',
        description: 'Library',
        placeType: 'Study',
        tags: [ 'Library', 'Printers' ],
        location: { type: 'Point', coordinates: [ 40.4276319, -86.91326409999999 ] },
        reviews: [],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Living',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Living',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Living',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Living',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Living',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Living',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Living',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Living',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: '',
        description: '',
        placeType: 'Living',
        tags: [ '' ],
        location: { type: 'Point', coordinates: [ ,  ] },
        reviews: [ ],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
    {
        name: 'Hillenbrand Hall',
        description: 'Residence Hall',
        placeType: 'Living',
        tags: [ 'Learning Community', 'Dining Court' ],
        location: {
          type: 'Point',
          coordinates: [ 40.42669962268096, -86.92667082832517 ]
        },
        reviews: [],
        images: [ ],
        address: '',
        googleMap: '',
        website: ''
    },
])